# Generated by Django 5.2.14 on 2026-07-23 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_recitation_track_folder_constraints'),
        ('quran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetVersionEntry',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('text', models.TextField(blank=True, help_text='Translation / tafsir text for this ayah')),
                ('footnotes', models.TextField(blank=True, help_text='Footnotes or margin content for this ayah')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (defaults to the canonical ayah index)')),
            ],
        ),
        migrations.AddField(
            model_name='assetversion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this version (e.g. started the draft).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetversion',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='published', help_text="Lifecycle state. Draft versions are excluded from 'latest' and public listings.", max_length=20),
        ),
        migrations.AddConstraint(
            model_name='assetversion',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'draft')), fields=('asset',), name='unique_draft_version_per_asset'),
        ),
        migrations.AddField(
            model_name='assetversionentry',
            name='ayah',
            field=models.ForeignKey(help_text='Canonical ayah (1-6236) this entry provides text for', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quran.ayah'),
        ),
        migrations.AddField(
            model_name='assetversionentry',
            name='version',
            field=models.ForeignKey(help_text='Asset version this entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='content.assetversion'),
        ),
        migrations.AddIndex(
            model_name='assetversionentry',
            index=models.Index(fields=['version', 'order'], name='content_ass_version_e15d96_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetversionentry',
            constraint=models.UniqueConstraint(fields=('version', 'ayah'), name='unique_entry_per_version_ayah'),
        ),
    ]
