# Generated by Django 5.2.14 on 2026-08-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_recitation_track_folder_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialRecommendation',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('title', models.CharField(help_text="Collection title, e.g. 'Ramadan Recitations'", max_length=255)),
                ('title_en', models.CharField(help_text="Collection title, e.g. 'Ramadan Recitations'", max_length=255, null=True)),
                ('title_ar', models.CharField(help_text="Collection title, e.g. 'Ramadan Recitations'", max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='', null=True)),
                ('description_ar', models.TextField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this collection is eligible to be served')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Optional start of the active window', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Optional end of the active window', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialRecommendationAsset',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated')),
                ('position', models.PositiveIntegerField(default=1, help_text='Display order within the collection')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_recommendation_assets', to='content.asset')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_assets', to='content.editorialrecommendation')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('recommendation', 'asset')},
            },
        ),
        migrations.AddField(
            model_name='editorialrecommendation',
            name='assets',
            field=models.ManyToManyField(related_name='editorial_recommendations', through='content.EditorialRecommendationAsset', to='content.asset'),
        ),
    ]
