# Generated by Django 5.2.14 on 2026-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_assetversionentry_assetversion_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetversion',
            name='content_edited',
            field=models.BooleanField(default=False, help_text="True once a draft's per-ayah entries have been edited after seeding. Publishing an unedited draft would just duplicate the latest version, so it is disallowed."),
        ),
    ]
