# Generated by Django 5.2.14 on 2026-08-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_editorialrecommendation_editorialrecommendationasset_and_more'),
        ('content', '0051_assetversion_content_edited'),
    ]

    operations = [
    ]
